[pytest]
addopts = -p no:hypothesispytest
pythonpath = backend
testpaths = backend/tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20
    ignore:.*ARC4 has been moved.*
