from datetime import datetime
from typing import Optional, Dict, Any, TYPE_CHECKING
from sqlmodel import SQLModel, Field, Relationship, JSON, Column

if TYPE_CHECKING:
    from app.models.source import Source


class Change(SQLModel, table=True):
    """Detected changes in scraped sources."""
    
    __tablename__ = "changes"
    
    id: Optional[int] = Field(default=None, primary_key=True)
    source_id: int = Field(foreign_key="sources.id", index=True)
    
    # Content hashes
    old_hash: str = Field(max_length=64)
    new_hash: str = Field(max_length=64)
    
    # Change summary (generated by LLM)
    diff_summary: str = Field()
    
    # Severity: low, medium, high, critical
    severity: str = Field(max_length=20, default="medium", index=True)
    
    # List of user IDs that were notified
    notified_users: Dict[str, Any] = Field(default={}, sa_column=Column(JSON))
    
    detected_at: datetime = Field(default_factory=datetime.utcnow, index=True)
    
    # Relationship
    source: "Source" = Relationship(back_populates="changes")
