[pytest]
addopts = -p no:hypothesispytest
pythonpath = .
testpaths = tests
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20
    ignore:.*ARC4 has been moved.*
